-- Supabase Schema for Project Trishul

-- Create the table for logging breakout signals
CREATE TABLE public.trishul_signals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ NOT NULL,
    ticker TEXT NOT NULL,
    direction TEXT NOT NULL,
    spoof_filtered_obi DOUBLE PRECISION,
    cvd_value DOUBLE PRECISION,
    avp_phase_status TEXT,
    micro_price DOUBLE PRECISION,
    sweep_vwap DOUBLE PRECISION,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Optional: Create an index on timestamp for faster time-series queries
CREATE INDEX idx_trishul_signals_timestamp ON public.trishul_signals (timestamp DESC);
